name: Create Docker Image and Push to DockerHub

on:
  push:
    branches:
      - foodapp_dev
    paths:
      - 'backend/**'
      - 'Dockerfile'

jobs:
  build-deploy:
    name: Build and Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          path: 'backend'
          fetch-depth: 1
          sparse-checkout: true
          sparse-checkout-config:
            - 'backend/'
            - 'Dockerfile'

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build The application
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          dockerfile: ../Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/foodapp:1.0.0
