name: Create Docker Image and Push to DockerHub

on:
  push:
    branches:
      - v2

jobs:
  build-deploy:
    name: Build and Deploy app
    runs-on: ubuntu-latest
    steps:
        - name: checkout the code
          uses: actions/checkout@v4

        - name: setup jdk
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: 17
        - name: Build The application
          run: |
            mvn clean package -DskipTests
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/foodapp:latest
            
         


