POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Ali",
  "lastname": "Bouali",
  "email":  "alibou@mail.com",
  "password": "password",
  "role":  "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token);  %}